// Generated by LiveScript 1.2.0
this.app.controller('ReservationCtrl', [
  '$scope', 'Restangular', function($scope, Restangular){
    $scope.reservations = Restangular.all('reservations/current').getList().$object;
    $scope.searchCheck = 'both';
    $scope.search = {};
    $scope.checkIn = function(reservation){
      Restangular.one('reservations', reservation.id).post('checkIn');
      reservation.checkInAvailable = false;
      reservation.checkedIn = true;
    };
    $scope.checkOut = function(reservation){
      if (confirm("Total price: " + reservation.fullPrice + " CHF")) {
        Restangular.one('reservations', reservation.id).post('checkOut');
        reservation.checkOutAvailable = false;
        reservation.checkedOut = true;
      }
    };
    return $scope.$watch('searchCheck', function(value){
      switch (value) {
      case 'both':
        delete $scope.search.checkInAvailable;
        delete $scope.search.checkOutAvailable;
        break;
      case 'in':
        $scope.search.checkInAvailable = true;
        $scope.search.checkOutAvailable = false;
        break;
      case 'out':
        $scope.search.checkInAvailable = false;
        $scope.search.checkOutAvailable = true;
      }
    });
  }
]);
this.app.controller('PurchaseCtrl', [
  '$scope', 'Restangular', '$state', '$stateParams', function($scope, Restangular, $state, $stateParams){
    $scope.submitPurchase = function(){
      Restangular.all('purchases').post($scope.purchase).then(function(){
        $scope.success = true;
      });
      $scope.purchaseSubmitted = true;
    };
    $scope.reset = function(){
      $state.go($state.$current, null, {
        reload: true
      });
    };
    $scope.purchase = {
      roomNumber: $stateParams.roomNumber
    };
    return $scope.$watch("purchase.roomNumber", function(roomNumber){
      if (roomNumber != null && roomNumber !== "") {
        Restangular.all('rooms').one('number', roomNumber).one('guest').get().then(function(guest){
          if (guest != null) {
            $scope.guest = guest;
            $scope.purchaseForm.roomNumber.$setValidity('correct', true);
          } else {
            $scope.guest = null;
            $scope.purchaseForm.roomNumber.$setValidity('correct', false);
          }
        });
      } else {
        $scope.guest = null;
        $scope.purchaseForm.roomNumber.$setValidity('correct', true);
      }
    });
  }
]);
this.app.controller('RoomCtrl', [
  '$scope', 'Restangular', function($scope, Restangular){
    var rooms;
    rooms = Restangular.all('rooms');
    $scope.loadRooms = function(){
      $scope.rooms = rooms.getList().$object;
    };
    $scope.loadRooms();
    $scope.edit = function(room){
      $scope.editedRoomOrig = room;
      $scope.editedRoom = Restangular.copy(room);
    };
    $scope.save = function(){
      if ($scope.editedRoom.id == null) {
        rooms.post($scope.editedRoom).then(function(){
          $scope.loadRooms();
        });
      } else {
        $scope.editedRoom.put();
      }
      angular.copy($scope.editedRoom, $scope.editedRoomOrig);
      $scope.editedRoom = null;
    };
    $scope.cancel = function(){
      if ($scope.editedRoom.id == null) {
        $scope.rooms.splice(0, 1);
      }
      $scope.editedRoom = null;
    };
    return $scope['new'] = function(){
      var editedRoom;
      editedRoom = {};
      $scope.rooms.unshift(editedRoom);
      $scope.editedRoom = editedRoom;
    };
  }
]);
